import os

os.system("python aaron.py --encodings encodings.pickle --attacker Aberdeen/hin1.jpg --victims Aberdeen/")
os.system("python aaron.py --encodings encodings.pickle --attacker Aberdeen/ian1.jpg --victims Aberdeen/")
os.system("python aaron.py --encodings encodings.pickle --attacker Aberdeen/irene1.jpg --victims Aberdeen/")
os.system("python aaron.py --encodings encodings.pickle --attacker Aberdeen/iroy1.jpg --victims Aberdeen/")
os.system("python aaron.py --encodings encodings.pickle --attacker Aberdeen/itaylor1.jpg --victims Aberdeen/")
os.system("python aaron.py --encodings encodings.pickle --attacker Aberdeen/jenni1.jpg --victims Aberdeen/")
os.system("python aaron.py --encodings encodings.pickle --attacker Aberdeen/jim1.jpg --victims Aberdeen/")
os.system("python aaron.py --encodings encodings.pickle --attacker Aberdeen/joanna1.jpg --victims Aberdeen/")
os.system("python aaron.py --encodings encodings.pickle --attacker Aberdeen/johannes1.jpg --victims Aberdeen/")
os.system("python aaron.py --encodings encodings.pickle --attacker Aberdeen/john_mccal1.jpg --victims Aberdeen/")
os.system("python aaron.py --encodings encodings.pickle --attacker Aberdeen/johnny_page1.jpg --victims Aberdeen/")
os.system("python aaron.py --encodings encodings.pickle --attacker Aberdeen/john_thom1.jpg --victims Aberdeen/")
os.system("python aaron.py --encodings encodings.pickle --attacker Aberdeen/jsheenan1.jpg --victims Aberdeen/")
os.system("python aaron.py --encodings encodings.pickle --attacker Aberdeen/kay1.jpg --victims Aberdeen/")
os.system("python aaron.py --encodings encodings.pickle --attacker Aberdeen/kieran1.jpg --victims Aberdeen/")
os.system("python aaron.py --encodings encodings.pickle --attacker Aberdeen/kim1.jpg --victims Aberdeen/")
